server:
  port: 8081

#openapi 3
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    config-url: ${springdoc.api-docs.path}/config
    displayRequestDuration: true
    layout: BaseLayout
    path: /index.html
    show-extensions: true
    url: ${springdoc.api-docs.path}
  cache:
    disabled: true


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketMessagingAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.reactive.WebSocketReactiveAutoConfiguration


ping:
  rest:
    web:
      representation-strategy: custom_mime
      meta-media-types:
        - json
        - xml
