spring:
  #数据源配置
  datasource:
    url: jdbc:h2:mem:ping;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: root
    password: 123456
    driver-class-name: org.h2.Driver

  #dev环境使用H2数据库
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect


  #h2数据库配置
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
