<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">


    <parent>
        <groupId>cn.procsl</groupId>
        <artifactId>ping</artifactId>
        <version>1.0.2-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>ping-distribute</artifactId>
    <name>Ping 应用服务</name>
    <packaging>jar</packaging>

    <properties>
        <liquibase.version>4.15.0</liquibase.version>
        <ping.version>1.0.2-SNAPSHOT</ping.version>
        <java.version>25</java.version>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <compiler.version>${java.version}</compiler.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <springdoc.version>3.0.3</springdoc.version>
        <mapstruct.version>1.5.3.Final</mapstruct.version>
        <google.auto.version>1.1.1</google.auto.version>
        <manifold.version>2024.1.16</manifold.version>
        <web.server.port>10000</web.server.port>
        <spring-dev>false</spring-dev>
        <dynamic.spring.profiles>unset</dynamic.spring.profiles>
        <windows.native.args/>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.procsl</groupId>
            <artifactId>ping-product</artifactId>
            <version>${ping.version}</version>
        </dependency>

        <dependency>
            <groupId>cn.procsl</groupId>
            <artifactId>ping-system</artifactId>
            <version>${ping.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-properties-migrator</artifactId>
            <scope>runtime</scope>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <finalName>${project.artifactId}-${database.type}-${ping.version}</finalName>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springdoc</groupId>
                    <artifactId>springdoc-openapi-maven-plugin</artifactId>
                    <version>1.5</version>
                    <executions>
                        <execution>
                            <id>pure-compile-generate</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <apiDocsUrl>http://localhost:10000/v3/api-docs</apiDocsUrl>
                        <outputFileName>openapi.json</outputFileName>
                        <outputDir>${project.build.directory}/spring-doc</outputDir>
                        <failOnError>true</failOnError>
                        <skip>false</skip>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.springdoc</groupId>
                            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                            <version>${springdoc.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>


<!--            <plugin>-->
<!--                <groupId>org.codehaus.mojo</groupId>-->
<!--                <artifactId>exec-maven-plugin</artifactId>-->
<!--                <version>3.1.0</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>fetch-openapi-json</id>-->
<!--                        <phase>prepare-package</phase>-->
<!--                        <goals>-->
<!--                            <goal>java</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->

<!--                            <mainClass>cn.procsl.ping.app.DistributeApplication</mainClass>-->

<!--                            <includeProjectDependencies>true</includeProjectDependencies>-->
<!--                            <includePluginDependencies>true</includePluginDependencies>-->
<!--                            <classpathScope>test</classpathScope>-->

<!--                            <systemProperties>-->
<!--                                <systemProperty>-->
<!--                                    <key>file.encoding</key>-->
<!--                                    <value>UTF-8</value>-->
<!--                                </systemProperty>-->
<!--                                <systemProperty>-->
<!--                                    <key>sun.stdout.encoding</key>-->
<!--                                    <value>UTF-8</value>-->
<!--                                </systemProperty>-->
<!--                                <systemProperty>-->
<!--                                    <key>sun.stderr.encoding</key>-->
<!--                                    <value>UTF-8</value>-->
<!--                                </systemProperty>-->
<!--                            </systemProperties>-->

<!--                            <arguments>-->
<!--                                <argument>&#45;&#45;openapi.export=true</argument>-->
<!--                                <argument>&#45;&#45;openapi.output.dir=${project.build.outputDirectory}/ping-api-doc/</argument>-->
<!--                                <argument>&#45;&#45;spring.profiles.active=h2,openapi,openapi-export</argument>-->
<!--                                <argument>&#45;&#45;server.port=0</argument>-->
<!--                                <argument>&#45;&#45;logging.level.root=INFO</argument>-->
<!--                                <argument>&#45;&#45;server.address=127.0.0.1</argument>-->
<!--                                <argument>&#45;&#45;springdoc.api-docs.enabled=true</argument>-->
<!--                            </arguments>-->

<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->

<!--                <dependencies>-->
<!--                    <dependency>-->
<!--                        <groupId>org.springdoc</groupId>-->
<!--                        <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>-->
<!--                        <version>${springdoc.version}</version>-->
<!--                    </dependency>-->
<!--                    <dependency>-->
<!--                        <groupId>com.h2database</groupId>-->
<!--                        <artifactId>h2</artifactId>-->
<!--                        <version>${h2.version}</version>-->
<!--                    </dependency>-->
<!--                    <dependency>-->
<!--                        <groupId>org.springdoc</groupId>-->
<!--                        <artifactId>springdoc-openapi-starter-common</artifactId>-->
<!--                        <version>${springdoc.version}</version>-->
<!--                    </dependency>-->
<!--                </dependencies>-->

<!--            </plugin>-->

            <!--            <plugin>-->
            <!--                <groupId>org.springdoc</groupId>-->
            <!--                <artifactId>springdoc-openapi-maven-plugin</artifactId>-->
            <!--                <version>1.5</version>-->
            <!--            </plugin>-->

            <!--            <plugin>-->
            <!--                <groupId>org.apache.maven.plugins</groupId>-->
            <!--                <artifactId>maven-compiler-plugin</artifactId>-->
            <!--                <configuration>-->
            <!--                    <release>${java.version}</release>-->
            <!--                    <encoding>${project.build.sourceEncoding}</encoding>-->

            <!--                    <annotationProcessorPaths>-->
            <!--                        <path>-->
            <!--                            <groupId>org.projectlombok</groupId>-->
            <!--                            <artifactId>lombok</artifactId>-->
            <!--                        </path>-->

            <!--                        <path>-->
            <!--                            <groupId>org.springframework.boot</groupId>-->
            <!--                            <artifactId>spring-boot-configuration-processor</artifactId>-->
            <!--                            <version>${springboot.version}</version>-->
            <!--                        </path>-->

            <!--                        <path>-->
            <!--                            <groupId>org.springframework</groupId>-->
            <!--                            <artifactId>spring-context-indexer</artifactId>-->
            <!--                            <version>${springboot.version}</version>-->
            <!--                            &lt;!&ndash;                            <version>${spring-framework.version}</version>&ndash;&gt;-->
            <!--                        </path>-->

            <!--                    </annotationProcessorPaths>-->

            <!--                    <verbose>true</verbose>-->
            <!--                    <showWarnings>true</showWarnings>-->
            <!--                    &lt;!&ndash;保留参数名称&ndash;&gt;-->
            <!--                    <maxmem>2048m</maxmem>-->
            <!--                    <compilerArgs>-->
            <!--                        <arg>-g</arg>-->
            <!--                        <arg>-Xlint:unchecked</arg>-->
            <!--                        <arg>-Xlint:deprecation</arg>-->
            <!--                        <arg>-parameters</arg>-->
            <!--                        <arg>-proc:full</arg>-->
            <!--                    </compilerArgs>-->
            <!--                </configuration>-->
            <!--            </plugin>-->


            <!--            <plugin>-->
            <!--                <groupId>org.apache.maven.plugins</groupId>-->
            <!--                <artifactId>maven-resources-plugin</artifactId>-->
            <!--                <configuration>-->
            <!--                    <encoding>utf-8</encoding>-->
            <!--                    <delimiters>-->
            <!--                        <delimiter>@</delimiter>-->
            <!--                    </delimiters>-->
            <!--                    &lt;!&ndash; 解决Spring boot引起的profile失效问题 &ndash;&gt;-->
            <!--                    <useDefaultDelimiters>false</useDefaultDelimiters>-->
            <!--                    &lt;!&ndash; 过滤后缀为p12、pem、pfx的证书文件 &ndash;&gt;-->
            <!--                    <nonFilteredFileExtensions>-->
            <!--                        <nonFilteredFileExtension>p12</nonFilteredFileExtension>-->
            <!--                        <nonFilteredFileExtension>cer</nonFilteredFileExtension>-->
            <!--                        <nonFilteredFileExtension>pem</nonFilteredFileExtension>-->
            <!--                        <nonFilteredFileExtension>pfx</nonFilteredFileExtension>-->
            <!--                        <nonFilteredFileExtension>jkx</nonFilteredFileExtension>-->
            <!--                    </nonFilteredFileExtensions>-->
            <!--                </configuration>-->
            <!--            </plugin>-->

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${springboot.version}</version>
                <configuration>
                    <mainClass>cn.procsl.ping.app.DistributeApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <id>process-aot</id>
                        <!-- 绑定到打包前的准备阶段 -->
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>process-aot</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>

    </build>

    <profiles>

        <profile>
            <id>undertow</id>
            <dependencies>

                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-undertow</artifactId>
                </dependency>

                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                    <exclusions>
                        <exclusion>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-tomcat</artifactId>
                        </exclusion>

                        <exclusion>
                            <groupId>org.apache.tomcat.embed</groupId>
                            <artifactId>tomcat-embed-websocket</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>

            </dependencies>
        </profile>

        <profile>
            <id>h2</id>
            <properties>
                <database.type>h2</database.type>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>com.h2database</groupId>
                    <artifactId>h2</artifactId>
                </dependency>

                <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-h2console -->
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-h2console</artifactId>
                    <scope>compile</scope>
                </dependency>

            </dependencies>

        </profile>

        <profile>
            <id>mysql8</id>

            <properties>
                <database.type>mysql8</database.type>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>com.mysql</groupId>
                    <artifactId>mysql-connector-j</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>postgresql</id>
            <properties>
                <database.type>postgresql</database.type>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>openapi</id>
            <dependencies>

                <dependency>
                    <groupId>org.springdoc</groupId>
                    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                    <version>${springdoc.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.springdoc</groupId>
                    <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                    <version>${springdoc.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.springdoc</groupId>
                    <artifactId>springdoc-openapi-starter-common</artifactId>
                    <version>${springdoc.version}</version>
                </dependency>

            </dependencies>

        </profile>

        <profile>
            <id>monitor</id>

            <dependencies>
                <dependency>
                    <groupId>de.codecentric</groupId>
                    <artifactId>spring-boot-admin-starter-client</artifactId>
                </dependency>

                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-actuator</artifactId>
                </dependency>

                <dependency>
                    <groupId>de.codecentric</groupId>
                    <artifactId>spring-boot-admin-starter-server</artifactId>
                </dependency>

            </dependencies>

            <dependencyManagement>
                <dependencies>
                    <dependency>
                        <groupId>de.codecentric</groupId>
                        <artifactId>spring-boot-admin-starter-client</artifactId>
                        <version>4.0.4</version>
                    </dependency>

                    <dependency>
                        <groupId>de.codecentric</groupId>
                        <artifactId>spring-boot-admin-starter-server</artifactId>
                        <version>4.0.4</version>
                    </dependency>
                </dependencies>
            </dependencyManagement>

        </profile>

        <profile>
            <id>dependency-check</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>7.3.2</version>
                        <configuration>
                            <skipProvidedScope>true</skipProvidedScope>
                        </configuration>

                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                </plugins>
            </build>
        </profile>

        <profile>
            <id>debug</id>
            <properties>
                <spring-dev>true</spring-dev>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-devtools</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>patch-windows-native</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <!-- 只有 Windows 才会激活这行赋值 -->
                <windows.native.args>-H:+UseWindowsVirtualMemory</windows.native.args>
            </properties>
        </profile>

        <profile>
            <id>native</id>
            <build>
                <plugins>

                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <!--                        <version>1.0.0</version>-->
                        <configuration>
                            <mainClass>cn.procsl.ping.app.DistributeApplication</mainClass>
                            <buildArgs>
                                <!-- 添加这一行：允许生成分析报告 -->
                                <buildArg>--emit build-report</buildArg>
                                <!-- 关键点：把上面定义的变量引用进来（实现动态追加） -->
                            </buildArgs>
                        </configuration>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>


    </profiles>


</project>
